name: Test Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16', '1.12' ]
    name: Test goef Package
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: make test
